version: '3'
services:

  mysql-db:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "3302:3306"
    networks:
      - mogi


  # Django web server
  django-web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: docker-web
    volumes:
      - .:/code
    command: "./wait-for-it.sh -h mysql-db -p 3306  -- su -m myuser -c './run_web.sh'"
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    networks:
      - mogi

  # Celery worker
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./wait-for-it.sh -h django-rabbitmq -p 15672 -- su -m myuser -c 'celery worker -A mogi_site.celery -l info  --concurrency 20'"
    volumes:
      - .:/code
    depends_on:
      - mysql-db
      - django-web
      - django-rabbitmq
    networks:
      - mogi

  django-rabbitmq:
    image: rabbitmq:management
    hostname: django-rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"  # we forward this port because it's useful for debugging
      - "15673:15672"  # here, we can access rabbitmq management plugin
    links:
      - mysql-db
    networks:
      - mogi

networks:
    mogi:
