"""
Django settings for dma_site project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
from kombu import Exchange, Queue
import os
# secret stuff (not for github!!!)
from .settings_secret import  *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# Run Environment
# can be either local (for tomnl), CaStLeS (birmingham university VM system of docker container
RUN_ENVIRONMENT = 'docker'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['147.188.141.120', '0.0.0.0', '192.168.58.128', '127.0.0.1', 'localhost', '172.31.10.181']

CRISPY_TEMPLATE_PACK = 'bootstrap'

if RUN_ENVIRONMENT == 'castles':
    MEDIA_ROOT = "/rds/projects/2016/viantm-dma/"
    MEDIA_URL = '/rds/projects/2016/viantm-dma/'
    edr_pth = '/rds/projects/2015/viantm-01/users/'
    METAB_PUBCHEM_SQLITE_PTH = '/rds/projects/2016/viantm-dma/external_data/pubchem_sqlite/pubchem_20180520_1422.db'
    # if galaxy is accessible on the same storage drive as the django instance
    GALAXY_ROOT_PATH = '/rds/bear-apps/handbuilt/software/galaxy/viantm-dev'
elif RUN_ENVIRONMENT == 'local':
    MEDIA_ROOT = '/home/tomnl/dma/'
    MEDIA_URL = '/home/tomnl/dma/'
    edr_pth = '/home/tomnl/data/'
    METAB_PUBCHEM_SQLITE_PTH = '/home/tomnl/Dropbox/pubchem_small_testing.db'
    # if galaxy is accessible on the same storage drive as the django instance
    GALAXY_ROOT_PATH = '/home/tomnl/galaxy_storage/'
elif RUN_ENVIRONMENT == 'docker':
    MEDIA_ROOT = '/home/tomnl/dma/'
    MEDIA_URL = '/home/tomnl/dma/'
    edr_pth = '/home/tomnl/data/'
    METAB_PUBCHEM_SQLITE_PTH = '/home/tomnl/Dropbox/pubchem_small_testing.db'
    # if galaxy is accessible on the same storage drive as the django instance
    GALAXY_ROOT_PATH = '/home/tomnl/galaxy_storage/'


# MEDIA_ROOT_GFILES = '/home/tomnl'



EXTERNAL_DATA_ROOTS = { 'RDS': {
                            'path': edr_pth,
                            'user_dirs': True,
                            'help_text': 'Research data store for current user',
                            'filepathfield': False   # if false will use charfield path, if true filepathfield will look
                                                    # recursively in a selected folder but will be to slow for complicated
                                                    # folder structure
                            }
                        }


EXCEL_SUPPORT = 'xlwt' # or 'openpyxl' or 'pyexcelerator'

REDIS_PORT = 6379
REDIS_DB = 0
REDIS_HOST = os.environ.get('REDIS_PORT_6379_TCP_ADDR', 'redis')

RABBIT_HOSTNAME = os.environ.get('RABBIT_PORT_5672_TCP', 'rabbit')

if RABBIT_HOSTNAME.startswith('tcp://'):
    RABBIT_HOSTNAME = RABBIT_HOSTNAME.split('//')[1]

BROKER_URL = os.environ.get('BROKER_URL',
                            '')
if not BROKER_URL:
    BROKER_URL = 'amqp://{user}:{password}@{hostname}/{vhost}/'.format(
        user=os.environ.get('RABBIT_ENV_USER', 'admin'),
        password=os.environ.get('RABBIT_ENV_RABBITMQ_PASS', 'mypass'),
        hostname=RABBIT_HOSTNAME,
        vhost=os.environ.get('RABBIT_ENV_VHOST', ''))

# We don't want to have dead connections stored on rabbitmq, so we have to negotiate using heartbeats
BROKER_HEARTBEAT = '?heartbeat=60'
if not BROKER_URL.endswith(BROKER_HEARTBEAT):
    BROKER_URL += BROKER_HEARTBEAT

BROKER_POOL_LIMIT = 1
BROKER_CONNECTION_TIMEOUT = 10

# Celery configuration

# configure queues, currently we have only one
CELERY_DEFAULT_QUEUE = 'default'
CELERY_QUEUES = (
    Queue('default', Exchange('default'), routing_key='default'),
)

# Sensible settings for celery
CELERY_ALWAYS_EAGER = False
CELERY_ACKS_LATE = True
CELERY_TASK_PUBLISH_RETRY = True
CELERY_DISABLE_RATE_LIMITS = False

# By default we will ignore result
# If you want to see results and try out tasks interactively, change it to False
# Or change this setting on tasks level
CELERY_IGNORE_RESULT = True
CELERY_SEND_TASK_ERROR_EMAILS = False
CELERY_TASK_RESULT_EXPIRES = 600

# Set redis as celery result backend
CELERY_RESULT_BACKEND = 'redis://%s:%d/%d' % (REDIS_HOST, REDIS_PORT, REDIS_DB)
CELERY_REDIS_MAX_CONNECTIONS = 1

# Don't use pickle as serializer, json is much safer
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ['application/json']

CELERYD_HIJACK_ROOT_LOGGER = False
CELERYD_PREFETCH_MULTIPLIER = 1
CELERYD_MAX_TASKS_PER_CHILD = 1000


LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = '/login/'


# Application definition # sitetree

INSTALLED_APPS = [


    'mogi_site',
    'mogi',
    'misa',
    'mbrowse',
    'galaxy',
    'gfiles',

    'dal',
    'dal_select2',
    'django_tables2',
    'rest_framework',
    'django_celery_results',
    'django_filters',
    'bootstrap3',
    'django_sb_admin',
    'django_tables2_column_shifter',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]
CKEDITOR_UPLOAD_PATH = "uploads/"
DJANGO_TABLES2_TEMPLATE = 'django_tables2/bootstrap.html'


# THUMBNAIL_HIGH_RESOLUTION = True   # for filer package
# FILER_ENABLE_PERMISSIONS = True

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # 'djangobower.finders.BowerFinder',
)

PROJECT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), ".."),
)

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

ROOT_URLCONF = 'mogi_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')), ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]



WSGI_APPLICATION = 'mogi_site.wsgi.application'

if RUN_ENVIRONMENT == 'castles':
    DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
          'NAME': 'tnl495',                      # Or path to database file if using sqlite3.
          'USER': 'tnl495',                      # Not used with sqlite3.
          'PASSWORD': DATABASE_PASS,                  # Not used with sqlite3.
          'HOST': 'bberdb.bham.ac.uk',                      # Set to empty string for localhost. Not used with sqlite3.
          'PORT': '3306',                      # Set to empty string for default. Not used with sqlite3.
       },
        'OPTIONS': {
            'connect_timeout': 50,
        }
    }
elif RUN_ENVIRONMENT == 'local':
    # Database
    # https://docs.djangoproject.com/en/1.9/ref/settings/#databases
    DATABASES = {
       'default': {
           'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
           'NAME': 'mogi',                      # Or path to database file if using sqlite3.
           'USER': 'tomnl',                      # Not used with sqlite3.
           'PASSWORD': DATABASE_PASS,                  # Not used with sqlite3.
           'HOST': '127.0.0.1',                      # Set to empty string for localhost. Not used with sqlite3.
           'PORT': '3306',                      # Set to empty string for default. Not used with sqlite3.
       }
    }
elif RUN_ENVIRONMENT == 'docker':
    # Database
    # https://docs.djangoproject.com/en/1.9/ref/settings/#databases
    DATABASES = {
         'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'docker',
            'USER': 'docker',
            'HOST': 'db',
            'PORT': '3306',
            'PASSWORD': 'docker',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL='/static/'

